name = "EmojiSymbols"
uuid = "c599478c-de41-4aed-94ea-b47665d7a42a"
keywords = ["emoji", "latex", "REPL"]
license = "MIT"
desc = "additional Emoji, LaTeX Symbols for Julia REPL ðŸ¤”"
authors = ["WooKyoung Noh <wookay.noh@gmail.com>"]
version = "0.1.11-DEV"

[deps]
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
LogicalOperators = "6ac76662-4673-4d6a-8390-a82adc3670cf"

[sources]
LogicalOperators = {url = "https://github.com/wookay/LogicalOperators.jl", rev = "main"}

[compat]
julia = "1"
LogicalOperators = "0.1"
Jive = "0.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Jive = "ba5e3d4b-8524-549f-bc71-e76ad9e9deed"

[targets]
test = ["Test", "Pkg", "Jive"]
